### ISSUE TITLE
NESTED PAGES PATH DOESNT SEEM ON URL

### ISSUE THREAD

**Issue by nnadir35** [FilledStacks/stacked#738]
```dart
@StackedApp(
  routes: [
    MaterialRoute(
      page: SplashView,
      initial: true,
      path: "/",
    ),
    MaterialRoute(
      page: OnboardView,
      path: onboardViewRoute,
    ),
    MaterialRoute(page: LoginView, path: loginViewRoute),
    MaterialRoute(page: MainView, path: mainViewRoute, children: [
      MaterialRoute(page: ProfileView, path: profileViewRoute),
      MaterialRoute(page: MenuView, path: menuViewRoute),
      MaterialRoute(page: TablesView, path: tablesViewRoute),
    ])
  ],
)
```

I see my pages path on url until mainview. When i came to main view stuck in the http://localhost:11227/#/main. Also i check my previousRoute is empty too. How can i fix this

```dart
    return Scaffold(
      resizeToAvoidBottomInset: false,
      body: ExtendedNavigator(
        initialRoute: MainViewRoutes.tablesView,
        router: MainViewRouter(),
        navigatorKey: StackedService.nestedNavigationKey(1),
      ),
    );
```
this extendednavigator use mainviewrouter which ancestor of profile, menu and tables

**Comment by FilledStacks** [comment]
Hey, the web support is limited, we're mainly focused on mobile apps. It's usable, but you'll need to do work to get your Urls to be perfect. 

In terms of the previousRoute being empty. You can add the StackedNavigatorObserver to your observers so that stacked can track the current and previous routes.
